// <auto-generated />
using FrituurTWiel.Products.Persistence.DataModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FrituurTWiel.Products.Persistence.DataModel.Migrations
{
    [DbContext(typeof(FrituurTWielDbContext))]
    [Migration("20260914110441_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FrituurTWiel.Products.Persistence.DataModel.Entities.ProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.ToTable("Products", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Available = true,
                            Category = "SAUS",
                            Description = "",
                            Name = "Mayonaise",
                            Price = 1.1m
                        },
                        new
                        {
                            Id = 2,
                            Available = true,
                            Category = "SAUS",
                            Description = "",
                            Name = "Ketchup",
                            Price = 1.1m
                        },
                        new
                        {
                            Id = 3,
                            Available = true,
                            Category = "SAUS",
                            Description = "",
                            Name = "Curry",
                            Price = 1.1m
                        },
                        new
                        {
                            Id = 4,
                            Available = true,
                            Category = "SAUS",
                            Description = "",
                            Name = "Samurai",
                            Price = 1.1m
                        },
                        new
                        {
                            Id = 5,
                            Available = true,
                            Category = "SAUS",
                            Description = "",
                            Name = "Andalouse",
                            Price = 1.1m
                        },
                        new
                        {
                            Id = 6,
                            Available = true,
                            Category = "SAUS",
                            Description = "",
                            Name = "Special saus",
                            Price = 2.5m
                        },
                        new
                        {
                            Id = 7,
                            Available = true,
                            Category = "FRIETJE",
                            Description = "",
                            Name = "Mini friet",
                            Price = 2.6m
                        },
                        new
                        {
                            Id = 8,
                            Available = true,
                            Category = "FRIETJE",
                            Description = "",
                            Name = "Klein friet",
                            Price = 3.0m
                        },
                        new
                        {
                            Id = 9,
                            Available = true,
                            Category = "FRIETJE",
                            Description = "",
                            Name = "Middel friet",
                            Price = 3.5m
                        },
                        new
                        {
                            Id = 10,
                            Available = true,
                            Category = "FRIETJE",
                            Description = "",
                            Name = "Groot friet",
                            Price = 4.0m
                        },
                        new
                        {
                            Id = 11,
                            Available = true,
                            Category = "FRIETJE",
                            Description = "",
                            Name = "Familiepak",
                            Price = 8.5m
                        },
                        new
                        {
                            Id = 12,
                            Available = true,
                            Category = "FRIETJE",
                            Description = "",
                            Name = "Romboutje",
                            Price = 8.5m
                        },
                        new
                        {
                            Id = 13,
                            Available = true,
                            Category = "FRIETJE",
                            Description = "",
                            Name = "Julienneke",
                            Price = 8.5m
                        },
                        new
                        {
                            Id = 14,
                            Available = true,
                            Category = "FRIETJE",
                            Description = "",
                            Name = "Frietje 't Wiel",
                            Price = 8.5m
                        },
                        new
                        {
                            Id = 15,
                            Available = true,
                            Category = "FRIETJE",
                            Description = "",
                            Name = "Kinderbox",
                            Price = 8.5m
                        },
                        new
                        {
                            Id = 16,
                            Available = true,
                            Category = "BICKY_BURGER",
                            Description = "",
                            Name = "Bicky Burger",
                            Price = 4.2m
                        },
                        new
                        {
                            Id = 17,
                            Available = true,
                            Category = "BICKY_BURGER",
                            Description = "",
                            Name = "Bicky Cheese",
                            Price = 4.5m
                        },
                        new
                        {
                            Id = 18,
                            Available = true,
                            Category = "BICKY_BURGER",
                            Description = "",
                            Name = "Bicky Chicken",
                            Price = 4.5m
                        },
                        new
                        {
                            Id = 19,
                            Available = true,
                            Category = "BICKY_BURGER",
                            Description = "",
                            Name = "Bicky Veggie",
                            Price = 4.5m
                        },
                        new
                        {
                            Id = 20,
                            Available = true,
                            Category = "HAMBURGER",
                            Description = "",
                            Name = "Hamburger",
                            Price = 4.0m
                        },
                        new
                        {
                            Id = 21,
                            Available = true,
                            Category = "HAMBURGER",
                            Description = "",
                            Name = "Cheeseburger",
                            Price = 4.5m
                        },
                        new
                        {
                            Id = 22,
                            Available = true,
                            Category = "HAMBURGER",
                            Description = "",
                            Name = "Chickenburger",
                            Price = 4.5m
                        },
                        new
                        {
                            Id = 23,
                            Available = true,
                            Category = "HAMBURGER",
                            Description = "",
                            Name = "Classic (ketchup)",
                            Price = 7.0m
                        },
                        new
                        {
                            Id = 24,
                            Available = true,
                            Category = "HAMBURGER",
                            Description = "",
                            Name = "Cheeseburger (kaas & ketchup)",
                            Price = 7.0m
                        },
                        new
                        {
                            Id = 25,
                            Available = true,
                            Category = "HAMBURGER",
                            Description = "",
                            Name = "Black Pepper burger",
                            Price = 7.0m
                        },
                        new
                        {
                            Id = 26,
                            Available = true,
                            Category = "HAMBURGER",
                            Description = "",
                            Name = "Tok Tok Kedei",
                            Price = 8.0m
                        },
                        new
                        {
                            Id = 27,
                            Available = true,
                            Category = "HAMBURGER",
                            Description = "",
                            Name = "Oh My God burger",
                            Price = 8.0m
                        },
                        new
                        {
                            Id = 28,
                            Available = true,
                            Category = "HAMBURGER",
                            Description = "",
                            Name = "Burger 'T Wiel",
                            Price = 8.0m
                        },
                        new
                        {
                            Id = 29,
                            Available = true,
                            Category = "PASTA",
                            Description = "",
                            Name = "Spaghetti",
                            Price = 9.0m
                        },
                        new
                        {
                            Id = 30,
                            Available = true,
                            Category = "PASTA",
                            Description = "",
                            Name = "Macaroni",
                            Price = 9.0m
                        },
                        new
                        {
                            Id = 31,
                            Available = true,
                            Category = "DRANK",
                            Description = "",
                            Name = "Cola",
                            Price = 2.5m
                        },
                        new
                        {
                            Id = 32,
                            Available = true,
                            Category = "DRANK",
                            Description = "",
                            Name = "Cola Zero",
                            Price = 2.5m
                        },
                        new
                        {
                            Id = 33,
                            Available = true,
                            Category = "DRANK",
                            Description = "",
                            Name = "Jupiler",
                            Price = 2.5m
                        },
                        new
                        {
                            Id = 34,
                            Available = true,
                            Category = "DRANK",
                            Description = "",
                            Name = "Fanta Lemon",
                            Price = 2.5m
                        },
                        new
                        {
                            Id = 35,
                            Available = true,
                            Category = "DRANK",
                            Description = "",
                            Name = "RedBull",
                            Price = 2.5m
                        },
                        new
                        {
                            Id = 36,
                            Available = true,
                            Category = "DRANK",
                            Description = "",
                            Name = "Sprite",
                            Price = 2.5m
                        },
                        new
                        {
                            Id = 37,
                            Available = true,
                            Category = "DRANK",
                            Description = "",
                            Name = "Ice Tea",
                            Price = 2.5m
                        },
                        new
                        {
                            Id = 38,
                            Available = true,
                            Category = "DRANK",
                            Description = "",
                            Name = "Water",
                            Price = 2.5m
                        },
                        new
                        {
                            Id = 39,
                            Available = true,
                            Category = "WARME_SAUS",
                            Description = "",
                            Name = "Stoofvleessaus",
                            Price = 2.2m
                        },
                        new
                        {
                            Id = 40,
                            Available = true,
                            Category = "WARME_SAUS",
                            Description = "",
                            Name = "Tomatensaus",
                            Price = 2.2m
                        },
                        new
                        {
                            Id = 41,
                            Available = true,
                            Category = "WARME_SAUS",
                            Description = "",
                            Name = "Spaghettisaus",
                            Price = 3.0m
                        },
                        new
                        {
                            Id = 42,
                            Available = true,
                            Category = "VERSE_BEREIDING",
                            Description = "",
                            Name = "Stoofvlees",
                            Price = 8.0m
                        },
                        new
                        {
                            Id = 43,
                            Available = true,
                            Category = "VERSE_BEREIDING",
                            Description = "",
                            Name = "Balletjes in tomatensaus",
                            Price = 8.0m
                        },
                        new
                        {
                            Id = 44,
                            Available = true,
                            Category = "VERSE_BEREIDING",
                            Description = "",
                            Name = "Vol-au-vent",
                            Price = 8.0m
                        },
                        new
                        {
                            Id = 45,
                            Available = true,
                            Category = "BELEGD_BROODJE",
                            Description = "",
                            Name = "Kaas broodje",
                            Price = 4.5m
                        },
                        new
                        {
                            Id = 46,
                            Available = true,
                            Category = "BELEGD_BROODJE",
                            Description = "",
                            Name = "Hesp broodje",
                            Price = 4.5m
                        },
                        new
                        {
                            Id = 47,
                            Available = true,
                            Category = "BELEGD_BROODJE",
                            Description = "",
                            Name = "Kaas en hesp",
                            Price = 4.8m
                        },
                        new
                        {
                            Id = 48,
                            Available = true,
                            Category = "WARM_BROODJE",
                            Description = "",
                            Name = "Boulet broodje",
                            Price = 7.0m
                        },
                        new
                        {
                            Id = 49,
                            Available = true,
                            Category = "WARM_BROODJE",
                            Description = "",
                            Name = "Mexicano broodje",
                            Price = 7.0m
                        },
                        new
                        {
                            Id = 50,
                            Available = true,
                            Category = "WARM_BROODJE",
                            Description = "",
                            Name = "Hamburger broodje",
                            Price = 8.0m
                        },
                        new
                        {
                            Id = 51,
                            Available = true,
                            Category = "WARM_BROODJE",
                            Description = "",
                            Name = "Stoofvleesschotel",
                            Price = 16.5m
                        },
                        new
                        {
                            Id = 52,
                            Available = true,
                            Category = "SCHOTEL",
                            Description = "",
                            Name = "Balletjesschotel",
                            Price = 16.5m
                        },
                        new
                        {
                            Id = 53,
                            Available = true,
                            Category = "SCHOTEL",
                            Description = "",
                            Name = "Vol-au-vent schotel",
                            Price = 16.5m
                        },
                        new
                        {
                            Id = 54,
                            Available = true,
                            Category = "SCHOTEL",
                            Description = "",
                            Name = "Frikandellenschotel (2)",
                            Price = 16.5m
                        },
                        new
                        {
                            Id = 55,
                            Available = true,
                            Category = "SCHOTEL",
                            Description = "",
                            Name = "Bouletten schotel (2)",
                            Price = 16.5m
                        },
                        new
                        {
                            Id = 56,
                            Available = true,
                            Category = "SCHOTEL",
                            Description = "",
                            Name = "Kip Korma Curry (rijst)",
                            Price = 16.5m
                        },
                        new
                        {
                            Id = 57,
                            Available = true,
                            Category = "SCHOTEL",
                            Description = "",
                            Name = "Scampi Diabolique",
                            Price = 18.5m
                        },
                        new
                        {
                            Id = 58,
                            Available = true,
                            Category = "SCHOTEL",
                            Description = "",
                            Name = "Paardenworstenschotel",
                            Price = 18.5m
                        },
                        new
                        {
                            Id = 59,
                            Available = true,
                            Category = "SCHOTEL",
                            Description = "",
                            Name = "Saté schotel (2)",
                            Price = 18.5m
                        },
                        new
                        {
                            Id = 60,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Frikandel",
                            Price = 2.2m
                        },
                        new
                        {
                            Id = 61,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Bitterballen",
                            Price = 3.2m
                        },
                        new
                        {
                            Id = 62,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Mexicano",
                            Price = 3.5m
                        },
                        new
                        {
                            Id = 63,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Kaaskroket",
                            Price = 2.6m
                        },
                        new
                        {
                            Id = 64,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Vleeskroket",
                            Price = 2.6m
                        },
                        new
                        {
                            Id = 65,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Chicken nuggets",
                            Price = 4.2m
                        },
                        new
                        {
                            Id = 66,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Frikandel special",
                            Price = 3.0m
                        },
                        new
                        {
                            Id = 67,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Boulet",
                            Price = 2.2m
                        },
                        new
                        {
                            Id = 68,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Boulet special",
                            Price = 3.0m
                        },
                        new
                        {
                            Id = 69,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Cervela",
                            Price = 3.0m
                        },
                        new
                        {
                            Id = 70,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Cervela special",
                            Price = 3.8m
                        },
                        new
                        {
                            Id = 71,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Frikandel XXL",
                            Price = 4.0m
                        },
                        new
                        {
                            Id = 72,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Viandel",
                            Price = 3.2m
                        },
                        new
                        {
                            Id = 73,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Spicy viandel",
                            Price = 3.2m
                        },
                        new
                        {
                            Id = 74,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Zigeunerstick",
                            Price = 3.8m
                        },
                        new
                        {
                            Id = 75,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Grizzly pikant",
                            Price = 4.0m
                        },
                        new
                        {
                            Id = 76,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Kipcorn",
                            Price = 3.2m
                        },
                        new
                        {
                            Id = 77,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Kaas soufflé",
                            Price = 2.6m
                        },
                        new
                        {
                            Id = 78,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "chixfingers",
                            Price = 4.2m
                        },
                        new
                        {
                            Id = 79,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Kippets",
                            Price = 4.2m
                        },
                        new
                        {
                            Id = 80,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Loempia met kip",
                            Price = 4.5m
                        },
                        new
                        {
                            Id = 81,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Kippenboutjes",
                            Price = 4.5m
                        },
                        new
                        {
                            Id = 82,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Mozzarellafingers",
                            Price = 4.0m
                        },
                        new
                        {
                            Id = 83,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Bamischijf",
                            Price = 3.5m
                        },
                        new
                        {
                            Id = 84,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Megamix",
                            Price = 5.0m
                        },
                        new
                        {
                            Id = 85,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Kaas kroket",
                            Price = 3.2m
                        },
                        new
                        {
                            Id = 86,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Vlees kroket",
                            Price = 3.2m
                        },
                        new
                        {
                            Id = 87,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Goulashkroket",
                            Price = 3.2m
                        },
                        new
                        {
                            Id = 88,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Garnaalkroket",
                            Price = 4.5m
                        },
                        new
                        {
                            Id = 89,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Taco",
                            Price = 3.5m
                        },
                        new
                        {
                            Id = 90,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Vuurvreter",
                            Price = 3.5m
                        },
                        new
                        {
                            Id = 91,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Kaasballetjes",
                            Price = 3.0m
                        },
                        new
                        {
                            Id = 92,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Ribster",
                            Price = 3.5m
                        },
                        new
                        {
                            Id = 93,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Nacho cheese bites",
                            Price = 4.5m
                        },
                        new
                        {
                            Id = 94,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Viandel speciaal",
                            Price = 4.0m
                        },
                        new
                        {
                            Id = 95,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Gakki",
                            Price = 3.5m
                        },
                        new
                        {
                            Id = 96,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Ragouzi",
                            Price = 3.5m
                        },
                        new
                        {
                            Id = 97,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Lucifer",
                            Price = 3.5m
                        },
                        new
                        {
                            Id = 98,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Pikanto",
                            Price = 3.0m
                        },
                        new
                        {
                            Id = 99,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Piknikker",
                            Price = 4.0m
                        },
                        new
                        {
                            Id = 100,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Saté",
                            Price = 4.6m
                        },
                        new
                        {
                            Id = 101,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Sito",
                            Price = 4.0m
                        },
                        new
                        {
                            Id = 102,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Mammoet (+saus)",
                            Price = 3.5m
                        },
                        new
                        {
                            Id = 103,
                            Available = true,
                            Category = "SNACK",
                            Description = "",
                            Name = "Mosseltjes in azijn",
                            Price = 4.0m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
